volumes:
  etc_wireguard:

services:
  wg-easy:
    #environment:
    #  Optional:
    #  - PORT=51821
    #  - HOST=0.0.0.0
    #  - INSECURE=false

    image: ghcr.io/wg-easy/wg-easy:15.2.1
    container_name: wg-easy
    networks:
      wg:
        ipv4_address: 10.42.42.42
        ipv6_address: fdcc:ad94:bacf:61a3::2a
      traefik: {}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wg-easy.rule=Host(`${HOST_URL}`)"
      - "traefik.http.routers.wg-easy.entrypoints=websecure"
      - "traefik.http.routers.wg-easy.service=wg-easy"
      - "traefik.http.services.wg-easy.loadbalancer.server.port=51821"  
    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
  traefik:
      image: traefik:3.6.6
      container_name: traefik
      restart: unless-stopped

      # environment:
        # Environment variables for AWS credentials (will use .env file)
        #- AWS_ACCESS_KEY_ID
        #- AWS_SECRET_ACCESS_KEY
        #- AWS_REGION
        #- AWS_HOSTED_ZONE_ID
      ports:
          - '80:80'
          - '443:443/tcp'
          - '443:443/udp'
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./config/traefik/traefik.yml:/traefik.yml:ro
          - ./config/traefik/dynamic.yml:/traefik_dynamic.yml:ro
          - ./config/traefik/acme.json:/acme.json
      networks:
          - traefik
networks:
  traefik:
      external: true 
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64
